name: CI

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check build health
        run: pnpm build

      - name: Check for regressions
        run: pnpm eslint:ci

      - name: Run tests
        run: pnpm test
